//
//  ISO3166.swift
//  Moody
//
//  Created by XueliangZhu on 12/1/16.
//  Copyright © 2016 ThoughtWorks. All rights reserved.
//

import Foundation

public struct ISO3166 {
    public enum Country: Int16 {
        case GUY = 328
        case POL = 616
        case LTU = 440
        case NIC = 558
        case ISL = 352
        case LAO = 418
        case BTN = 64
        case PLW = 585
        case HKG = 344
        case CZE = 203
        case DZA = 12
        case CIV = 384
        case GRL = 304
        case MSR = 500
        case CUB = 192
        case BWA = 72
        case NOR = 578
        case SWZ = 748
        case FIN = 246
        case UGA = 800
        case ALB = 8
        case CYM = 136
        case ERI = 232
        case BLZ = 84
        case MNP = 580
        case TUR = 792
        case HUN = 348
        case SJM = 744
        case VEN = 862
        case EGY = 818
        case NRU = 520
        case TWN = 158
        case MEX = 484
        case ABW = 533
        case VGB = 92
        case GAB = 266
        case CAN = 124
        case IMN = 833
        case GUM = 316
        case SEN = 686
        case GIB = 292
        case COK = 184
        case TUV = 798
        case BRB = 52
        case BDI = 108
        case BLM = 652
        case SSD = 728
        case SYC = 690
        case GHA = 288
        case LVA = 428
        case NAM = 516
        case BRN = 96
        case NLD = 528
        case JOR = 400
        case GLP = 312
        case CHE = 756
        case AIA = 660
        case SVK = 703
        case COM = 174
        case IRL = 372
        case SHN = 654
        case BVT = 74
        case MLT = 470
        case SGP = 702
        case TON = 776
        case TGO = 768
        case NZL = 554
        case BEL = 56
        case SLE = 694
        case JPN = 392
        case VUT = 548
        case BMU = 60
        case MAC = 446
        case NPL = 524
        case MDV = 462
        case KGZ = 417
        case TUN = 788
        case PRT = 620
        case TTO = 780
        case IND = 356
        case PRY = 600
        case NER = 562
        case LIE = 438
        case BHS = 44
        case KAZ = 398
        case DNK = 208
        case CRI = 188
        case PHL = 608
        case NFK = 574
        case BES = 535
        case LBN = 422
        case FRO = 234
        case DOM = 214
        case BLR = 112
        case CHN = 156
        case VAT = 336
        case GRD = 308
        case BRA = 76
        case GMB = 270
        case MNG = 496
        case TCD = 148
        case MWI = 454
        case LBR = 430
        case MOZ = 508
        case AGO = 24
        case KNA = 659
        case ATG = 28
        case URY = 858
        case GRC = 300
        case ARM = 51
        case HMD = 334
        case ESP = 724
        case CUW = 531
        case CPV = 132
        case COD = 180
        case MLI = 466
        case DMA = 212
        case KHM = 116
        case AUS = 36
        case COG = 178
        case BEN = 204
        case FSM = 583
        case PSE = 275
        case ARE = 784
        case GIN = 324
        case BFA = 854
        case IRQ = 368
        case BHR = 48
        case AUT = 40
        case IOT = 86
        case SOM = 706
        case AFG = 4
        case ZAF = 710
        case DJI = 262
        case HND = 340
        case MHL = 584
        case RUS = 643
        case VCT = 670
        case EST = 233
        case GBR = 826
        case QAT = 634
        case MTQ = 474
        case PER = 604
        case ECU = 218
        case SRB = 688
        case JAM = 388
        case MKD = 807
        case COL = 170
        case KOR = 410
        case TLS = 626
        case LCA = 662
        case TZA = 834
        case SMR = 674
        case HTI = 332
        case GTM = 320
        case LSO = 426
        case DEU = 276
        case MMR = 104
        case IDN = 360
        case NCL = 540
        case PAK = 586
        case HRV = 191
        case ESH = 732
        case FLK = 238
        case PAN = 591
        case IRN = 364
        case AND = 20
        case UMI = 581
        case SVN = 705
        case BIH = 70
        case FRA = 250
        case TCA = 796
        case KWT = 414
        case STP = 678
        case ANT = 530
        case TKM = 795
        case TKL = 772
        case CYP = 196
        case ETH = 231
        case PRK = 408
        case SGS = 239
        case GGY = 831
        case YEM = 887
        case MUS = 480
        case AZE = 31
        case GUF = 254
        case CXR = 162
        case KEN = 404
        case LKA = 144
        case ASM = 16
        case PYF = 258
        case RWA = 646
        case ATF = 260
        case MDG = 450
        case MRT = 478
        case SXM = 534
        case FJI = 242
        case PNG = 598
        case LUX = 442
        case MDA = 498
        case ISR = 376
        case BOL = 68
        case SAU = 682
        case SWE = 752
        case SPM = 666
        case USA = 840
        case CAF = 140
        case SDN = 736
        case SLB = 90
        case ZMB = 894
        case CCK = 166
        case ALA = 248
        case KIR = 296
        case MYS = 458
        case MYT = 175
        case MCO = 492
        case PRI = 630
        case ROU = 642
        case VNM = 704
        case THA = 764
        case VIR = 850
        case ATA = 10
        case ARG = 32
        case BGR = 100
        case CHL = 152
        case TJK = 762
        case WSM = 882
        case NIU = 570
        case ITA = 380
        case GEO = 268
        case WLF = 876
        case JEY = 832
        case GNQ = 226
        case CMR = 120
        case GNB = 624
        case REU = 638
        case ZWE = 716
        case UKR = 804
        case PCN = 612
        case MAR = 504
        case UZB = 860
        case BGD = 50
        case MAF = 663
        case SUR = 740
        case SYR = 760
        case SLV = 222
        case LBY = 434
        case OMN = 512
        case MNE = 499
        case NGA = 566
        case Unknown = 0
    }
    public enum Continent: Int16 {
        case NA = 10001
        case AN = 10002
        case EU = 10003
        case AF = 10004
        case AS = 10005
        case SA = 10006
        case OC = 10007
    }
}

extension ISO3166.Country {
    public var threeLetterName: String {
        switch self {
        case .GUY: return "guy"
        case .POL: return "pol"
        case .LTU: return "ltu"
        case .NIC: return "nic"
        case .ISL: return "isl"
        case .LAO: return "lao"
        case .BTN: return "btn"
        case .PLW: return "plw"
        case .HKG: return "hkg"
        case .CZE: return "cze"
        case .DZA: return "dza"
        case .CIV: return "civ"
        case .GRL: return "grl"
        case .MSR: return "msr"
        case .CUB: return "cub"
        case .BWA: return "bwa"
        case .NOR: return "nor"
        case .SWZ: return "swz"
        case .FIN: return "fin"
        case .UGA: return "uga"
        case .ALB: return "alb"
        case .CYM: return "cym"
        case .ERI: return "eri"
        case .BLZ: return "blz"
        case .MNP: return "mnp"
        case .TUR: return "tur"
        case .HUN: return "hun"
        case .SJM: return "sjm"
        case .VEN: return "ven"
        case .EGY: return "egy"
        case .NRU: return "nru"
        case .TWN: return "twn"
        case .MEX: return "mex"
        case .ABW: return "abw"
        case .VGB: return "vgb"
        case .GAB: return "gab"
        case .CAN: return "can"
        case .IMN: return "imn"
        case .GUM: return "gum"
        case .SEN: return "sen"
        case .GIB: return "gib"
        case .COK: return "cok"
        case .TUV: return "tuv"
        case .BRB: return "brb"
        case .BDI: return "bdi"
        case .BLM: return "blm"
        case .SSD: return "ssd"
        case .SYC: return "syc"
        case .GHA: return "gha"
        case .LVA: return "lva"
        case .NAM: return "nam"
        case .BRN: return "brn"
        case .NLD: return "nld"
        case .JOR: return "jor"
        case .GLP: return "glp"
        case .CHE: return "che"
        case .AIA: return "aia"
        case .SVK: return "svk"
        case .COM: return "com"
        case .IRL: return "irl"
        case .SHN: return "shn"
        case .BVT: return "bvt"
        case .MLT: return "mlt"
        case .SGP: return "sgp"
        case .TON: return "ton"
        case .TGO: return "tgo"
        case .NZL: return "nzl"
        case .BEL: return "bel"
        case .SLE: return "sle"
        case .JPN: return "jpn"
        case .VUT: return "vut"
        case .BMU: return "bmu"
        case .MAC: return "mac"
        case .NPL: return "npl"
        case .MDV: return "mdv"
        case .KGZ: return "kgz"
        case .TUN: return "tun"
        case .PRT: return "prt"
        case .TTO: return "tto"
        case .IND: return "ind"
        case .PRY: return "pry"
        case .NER: return "ner"
        case .LIE: return "lie"
        case .BHS: return "bhs"
        case .KAZ: return "kaz"
        case .DNK: return "dnk"
        case .CRI: return "cri"
        case .PHL: return "phl"
        case .NFK: return "nfk"
        case .BES: return "bes"
        case .LBN: return "lbn"
        case .FRO: return "fro"
        case .DOM: return "dom"
        case .BLR: return "blr"
        case .CHN: return "chn"
        case .VAT: return "vat"
        case .GRD: return "grd"
        case .BRA: return "bra"
        case .GMB: return "gmb"
        case .MNG: return "mng"
        case .TCD: return "tcd"
        case .MWI: return "mwi"
        case .LBR: return "lbr"
        case .MOZ: return "moz"
        case .AGO: return "ago"
        case .KNA: return "kna"
        case .ATG: return "atg"
        case .URY: return "ury"
        case .GRC: return "grc"
        case .ARM: return "arm"
        case .HMD: return "hmd"
        case .ESP: return "esp"
        case .CUW: return "cuw"
        case .CPV: return "cpv"
        case .COD: return "cod"
        case .MLI: return "mli"
        case .DMA: return "dma"
        case .KHM: return "khm"
        case .AUS: return "aus"
        case .COG: return "cog"
        case .BEN: return "ben"
        case .FSM: return "fsm"
        case .PSE: return "pse"
        case .ARE: return "are"
        case .GIN: return "gin"
        case .BFA: return "bfa"
        case .IRQ: return "irq"
        case .BHR: return "bhr"
        case .AUT: return "aut"
        case .IOT: return "iot"
        case .SOM: return "som"
        case .AFG: return "afg"
        case .ZAF: return "zaf"
        case .DJI: return "dji"
        case .HND: return "hnd"
        case .MHL: return "mhl"
        case .RUS: return "rus"
        case .VCT: return "vct"
        case .EST: return "est"
        case .GBR: return "gbr"
        case .QAT: return "qat"
        case .MTQ: return "mtq"
        case .PER: return "per"
        case .ECU: return "ecu"
        case .SRB: return "srb"
        case .JAM: return "jam"
        case .MKD: return "mkd"
        case .COL: return "col"
        case .KOR: return "kor"
        case .TLS: return "tls"
        case .LCA: return "lca"
        case .TZA: return "tza"
        case .SMR: return "smr"
        case .HTI: return "hti"
        case .GTM: return "gtm"
        case .LSO: return "lso"
        case .DEU: return "deu"
        case .MMR: return "mmr"
        case .IDN: return "idn"
        case .NCL: return "ncl"
        case .PAK: return "pak"
        case .HRV: return "hrv"
        case .ESH: return "esh"
        case .FLK: return "flk"
        case .PAN: return "pan"
        case .IRN: return "irn"
        case .AND: return "and"
        case .UMI: return "umi"
        case .SVN: return "svn"
        case .BIH: return "bih"
        case .FRA: return "fra"
        case .TCA: return "tca"
        case .KWT: return "kwt"
        case .STP: return "stp"
        case .ANT: return "ant"
        case .TKM: return "tkm"
        case .TKL: return "tkl"
        case .CYP: return "cyp"
        case .ETH: return "eth"
        case .PRK: return "prk"
        case .SGS: return "sgs"
        case .GGY: return "ggy"
        case .YEM: return "yem"
        case .MUS: return "mus"
        case .AZE: return "aze"
        case .GUF: return "guf"
        case .CXR: return "cxr"
        case .KEN: return "ken"
        case .LKA: return "lka"
        case .ASM: return "asm"
        case .PYF: return "pyf"
        case .RWA: return "rwa"
        case .ATF: return "atf"
        case .MDG: return "mdg"
        case .MRT: return "mrt"
        case .SXM: return "sxm"
        case .FJI: return "fji"
        case .PNG: return "png"
        case .LUX: return "lux"
        case .MDA: return "mda"
        case .ISR: return "isr"
        case .BOL: return "bol"
        case .SAU: return "sau"
        case .SWE: return "swe"
        case .SPM: return "spm"
        case .USA: return "usa"
        case .CAF: return "caf"
        case .SDN: return "sdn"
        case .SLB: return "slb"
        case .ZMB: return "zmb"
        case .CCK: return "cck"
        case .ALA: return "ala"
        case .KIR: return "kir"
        case .MYS: return "mys"
        case .MYT: return "myt"
        case .MCO: return "mco"
        case .PRI: return "pri"
        case .ROU: return "rou"
        case .VNM: return "vnm"
        case .THA: return "tha"
        case .VIR: return "vir"
        case .ATA: return "ata"
        case .ARG: return "arg"
        case .BGR: return "bgr"
        case .CHL: return "chl"
        case .TJK: return "tjk"
        case .WSM: return "wsm"
        case .NIU: return "niu"
        case .ITA: return "ita"
        case .GEO: return "geo"
        case .WLF: return "wlf"
        case .JEY: return "jey"
        case .GNQ: return "gnq"
        case .CMR: return "cmr"
        case .GNB: return "gnb"
        case .REU: return "reu"
        case .ZWE: return "zwe"
        case .UKR: return "ukr"
        case .PCN: return "pcn"
        case .MAR: return "mar"
        case .UZB: return "uzb"
        case .BGD: return "bgd"
        case .MAF: return "maf"
        case .SUR: return "sur"
        case .SYR: return "syr"
        case .SLV: return "slv"
        case .LBY: return "lby"
        case .OMN: return "omn"
        case .MNE: return "mne"
        case .NGA: return "nga"
        default: return "Unknown"
        }
    }
}

extension ISO3166.Country: LocalizedStringConvertible {
    public var localizedDescription: String {
        let loc = NSLocale.current as NSLocale
        return loc.displayName(forKey: NSLocale.Key.countryCode, value: threeLetterName) ?? NSLocalizedString("country.Unknown", tableName: nil, bundle: Bundle(for: Continent.self), value: "country.Unknown", comment: "")
    }
}

extension ISO3166.Continent: LocalizedStringConvertible {
    public var localizedDescription: String { return String(describing: self) }
}
